# Generated by Django 3.0.6 on 2020-06-03 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0007_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likes',
        ),
    ]
