# Generated by Django 3.0.6 on 2020-06-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0009_auto_20200603_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(default='default/profile.png', upload_to='Profiles'),
        ),
    ]
