# Generated by Django 3.0.6 on 2020-06-07 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0015_auto_20200606_1715'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
