# Generated by Django 2.1.15 on 2020-06-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0019_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
